language: php
sudo: false

matrix:
  include:
    - php: "7.2"
    - php: "7.3"
    
services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbhelper_tests;'
  - mysql -u root --default-character-set=utf8 dbhelper_tests < tests/assets/sql/tests.sql